feat: add CATE token
axelarnetwork/axelar-configs pull request #109
Opened 2024-08-13 06:19 UTC by catecoins

2024-08-15 00:16 UTC, Olanetsoft requested changes
Could you please add your logo? @catecoins See and example PR [here](https://github.com/axelarnetwork/axelar-configs/pull/80). We will get this merged as soon as you update the PR with the logo. Thank you.

2024-08-15 00:30 UTC, catecoins commented
![imgpsh_fullsize_anim](https://github.com/user-attachments/assets/01a83fa5-f086-4574-9edb-d13e207263a2)

2024-08-16 14:01 UTC, Olanetsoft approved these changes

2024-08-18 16:26 UTC, ecdsafu approved these changes
lgtm @catecoins if there is a coinGeckoId for this token, could you add it? Otherwise, all good.

2024-08-19 21:18 UTC, merged