feat: add MOLLARS token
axelarnetwork/axelar-configs pull request #113
Opened 2024-08-17 22:17 UTC by divi-code

Adding New Ethereum token to the List, MOLLARS. Below is the project information.

Website - https://mollars.com/
Coinmarketcap - https://coinmarketcap.com/currencies/mollarstoken/
Coingecko - https://www.coingecko.com/en/coins/mollarstoken

2024-08-18 16:23 UTC, ecdsafu approved these changes
lgtm

2024-08-19 21:20 UTC, canhtrinh requested changes
this PR is missing an icon. this URL does not exist: https://raw.githubusercontent.com/axelarnetwork/axelar-configs/main/images/tokens/mollars.svg

2024-08-19 21:21 UTC, canhtrinh commented
ah, nvm. i see the separate PR with the logo

2024-08-19 21:24 UTC, canhtrinh approved these changes

2024-08-19 21:25 UTC, merged