feat: add agETH token
axelarnetwork/axelar-configs pull request #127
Opened 2024-09-17 05:21 UTC by galacticminter

Adding Kelp's agETH config to whitelist on ITS.

2024-09-17 12:09 UTC, Olanetsoft requested changes
@galacticminter, kindly add your logo/icon.

2024-09-17 15:12 UTC, galacticminter commented
Hi @Olanetsoft, am I able to call these tokens on L2s as axl_agETH ? Is that convention fine ?

2024-09-18 13:26 UTC, Olanetsoft commented
> Hi @Olanetsoft, am I able to call these tokens on L2s as axl_agETH ? Is that convention fine ?

Any reason for doing this?

2024-09-18 19:17 UTC, galacticminter commented
We have a canonical token called agETH or wagETH on these L2s. Wouldn't want axelar tokens to be called with the same name.

2024-09-19 14:05 UTC, Olanetsoft commented
> We have a canonical token called agETH or wagETH on these L2s. Wouldn't want axelar tokens to be called with the same name. @Olanetsoft

@galacticminter I see. You can't rename the token `agETH` on a chain, i see that's what its registered as [here](https://etherscan.io/token/0xe1b4d34e8754600962cd944b535180bd758e6c2e). You won't be able to change the chain name on the chain itself. ERC20s don't support something like a changeName function. 

Alternatively, if you have a UI, you can map the proposed name to the name on-chain, e.g., `"agETH": "axl_agETH," so that any time someone tries to load agETH, you can show on your UI the axl-prefixed name.

2024-09-19 16:47 UTC, galacticminter commented
Sounds good @Olanetsoft 

Could you please approve & merge this?

2024-09-20 01:06 UTC, Olanetsoft approved these changes

2024-09-20 01:09 UTC, Olanetsoft commented
@galacticminter, one last thing. Could you please add your coingecko id ? eg. "coinGeckoId": "your-id".

2024-09-22 14:32 UTC, ecdsafu commented
@galacticminter on the Squid front end they'll be displayed using a prettySymbol, that we can edit as you like. Please let me know the preferred symbol on each chain

2024-09-22 14:33 UTC, ecdsafu approved these changes
lgtm

2024-09-23 05:29 UTC, galacticminter commented
Please use the pretty symbol as axl_agETH

2024-09-23 10:07 UTC, ecdsafu commented
> Please use the pretty symbol as axl_agETH

Sounds good. In Squid we are switching to the standard agETH.axl is that ok with you? We think it reads much better and is consistent with other bridge notations, such as USDC.e for ESDU bridged from ethereum native bridge

2024-09-23 15:50 UTC, canhtrinh commented
> > Please use the pretty symbol as axl_agETH
> 
> Sounds good. In Squid we are switching to the standard agETH.axl is that ok with you? We think it reads much better and is consistent with other bridge notations, such as USDC.e for ESDU bridged from ethereum native bridge

@ecdsafu - Jake from our BD team confirmed with theirs that your proposal is okay. Do you need to reflect that symbol here or do you have a separate mapping elsewhere that does that? If the latter, I will merge this PR rn

2024-09-24 14:24 UTC, Olanetsoft commented
> > > Please use the pretty symbol as axl_agETH
> > 
> > 
> > Sounds good. In Squid we are switching to the standard agETH.axl is that ok with you? We think it reads much better and is consistent with other bridge notations, such as USDC.e for ESDU bridged from ethereum native bridge
> 
> @ecdsafu - Jake from our BD team confirmed with theirs that your proposal is okay. Do you need to reflect that symbol here or do you have a separate mapping elsewhere that does that? If the latter, I will merge this PR rn

Friendly bump @ecdsafu ^

2024-09-24 20:38 UTC, ecdsafu reviewed
Please update the prettySymbol to be agETH.axl and then we can merge and release

2024-09-24 21:02 UTC, canhtrinh commented on registry/mainnet/interchain/squid.tokenlist.json
> +      "prettySymbol": "agETH",
```suggestion
      "prettySymbol": "agETH.axl",
```

2024-09-24 21:03 UTC, canhtrinh approved these changes

2024-09-24 21:03 UTC, merged