feat: add FUN token
axelarnetwork/axelar-configs pull request #135
Opened 2024-10-22 18:41 UTC by santiago-funtoken

2024-10-25 17:14 UTC, blurrytweaks requested changes
Hi! could you please add it's "coingeckoId": `"funfair"` below "tokenId" and change it's "name" to `"FUNToken"` since it was rebranded : )
Also, please add the .svg TokenImg, thanks in advance.

2024-10-28 13:16 UTC, santiago-funtoken commented
> Hi! could you please add it's "coingeckoId": `"funfair"` below "tokenId" and change it's "name" to `"FUNToken"` since it was rebranded : ) Also, please add the .svg TokenImg, thanks in advance.

Done, thanks for the review!

2024-10-28 13:18 UTC, blurrytweaks approved these changes
lgtm, thanks to you!

2024-10-29 18:08 UTC, Olanetsoft approved these changes

2024-10-29 18:08 UTC, merged