Add MOON token
axelarnetwork/axelar-configs pull request #29
Opened 2024-03-07 13:35 UTC by axldefi

2024-03-11 20:21 UTC, ecdsafu requested changes
For this token icon we'll need a png in order to keep the size down. Could you please use this instead? Just exported it to have a file size of <32kb. You're welcome to provide your own if you have one that's better.

![moon](https://github.com/axelarnetwork/axelar-configs/assets/36089395/616de1a4-b982-4a7b-968f-484a9fc7d595)

2024-03-13 09:47 UTC, axldefi commented
> For this token icon we'll need a png in order to keep the size down. Could you please use this instead? Just exported it to have a file size of <32kb. You're welcome to provide your own if you have one that's better.
> 
> ![moon](https://private-user-images.githubusercontent.com/36089395/311855758-616de1a4-b982-4a7b-968f-484a9fc7d595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjM1MzcsIm5iZiI6MTcxMDMyMzIzNywicGF0aCI6Ii8zNjA4OTM5NS8zMTE4NTU3NTgtNjE2ZGUxYTQtYjk4Mi00YTdiLTk2OGYtNDg0YTlmYzdkNTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA5NDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZWZlYmQ3ZjVlNzg3NzViMmYwOGMwZjg0ODEzMTRiYjZjNWQ0MmI1NjY5NDE3ZmI0ZWNhYjE0YzA5Njk3NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rUZTS4ZcBSigHOVZvhOz_INC0KGYcmRUIjY40EgaRo8)

I'm perfectly good with that version of the token, thank you!

2024-03-14 02:48 UTC, canhtrinh commented
> > For this token icon we'll need a png in order to keep the size down. Could you please use this instead? Just exported it to have a file size of <32kb. You're welcome to provide your own if you have one that's better.
> > ![moon](https://private-user-images.githubusercontent.com/36089395/311855758-616de1a4-b982-4a7b-968f-484a9fc7d595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjM1MzcsIm5iZiI6MTcxMDMyMzIzNywicGF0aCI6Ii8zNjA4OTM5NS8zMTE4NTU3NTgtNjE2ZGUxYTQtYjk4Mi00YTdiLTk2OGYtNDg0YTlmYzdkNTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA5NDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZWZlYmQ3ZjVlNzg3NzViMmYwOGMwZjg0ODEzMTRiYjZjNWQ0MmI1NjY5NDE3ZmI0ZWNhYjE0YzA5Njk3NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rUZTS4ZcBSigHOVZvhOz_INC0KGYcmRUIjY40EgaRo8)
> 
> I'm perfectly good with that version of the token, thank you!

we'll need svgs. @axldefi any way you can take that png and convert that to a low(er)-fidelity svg?

2024-03-14 08:20 UTC, axldefi commented
> > > For this token icon we'll need a png in order to keep the size down. Could you please use this instead? Just exported it to have a file size of <32kb. You're welcome to provide your own if you have one that's better.
> > > ![moon](https://private-user-images.githubusercontent.com/36089395/311855758-616de1a4-b982-4a7b-968f-484a9fc7d595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjM1MzcsIm5iZiI6MTcxMDMyMzIzNywicGF0aCI6Ii8zNjA4OTM5NS8zMTE4NTU3NTgtNjE2ZGUxYTQtYjk4Mi00YTdiLTk2OGYtNDg0YTlmYzdkNTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA5NDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZWZlYmQ3ZjVlNzg3NzViMmYwOGMwZjg0ODEzMTRiYjZjNWQ0MmI1NjY5NDE3ZmI0ZWNhYjE0YzA5Njk3NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rUZTS4ZcBSigHOVZvhOz_INC0KGYcmRUIjY40EgaRo8)
> > 
> > 
> > I'm perfectly good with that version of the token, thank you!
> 

> we'll need svgs. @axldefi any way you can take that png and convert that to a low(er)-fidelity svg?

will this work? 

![moon (2)](https://github.com/axelarnetwork/axelar-configs/assets/30039844/fa559726-f31a-4a65-a38d-f88c7bd1e787)

2024-04-15 20:04 UTC, ecdsafu commented
> > > > For this token icon we'll need a png in order to keep the size down. Could you please use this instead? Just exported it to have a file size of <32kb. You're welcome to provide your own if you have one that's better.
> > > > ![moon](https://private-user-images.githubusercontent.com/36089395/311855758-616de1a4-b982-4a7b-968f-484a9fc7d595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjM1MzcsIm5iZiI6MTcxMDMyMzIzNywicGF0aCI6Ii8zNjA4OTM5NS8zMTE4NTU3NTgtNjE2ZGUxYTQtYjk4Mi00YTdiLTk2OGYtNDg0YTlmYzdkNTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA5NDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZWZlYmQ3ZjVlNzg3NzViMmYwOGMwZjg0ODEzMTRiYjZjNWQ0MmI1NjY5NDE3ZmI0ZWNhYjE0YzA5Njk3NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rUZTS4ZcBSigHOVZvhOz_INC0KGYcmRUIjY40EgaRo8)
> > > 
> > > 
> > > I'm perfectly good with that version of the token, thank you!
> 
> > we'll need svgs. @axldefi any way you can take that png and convert that to a low(er)-fidelity svg?
> 
> will this work?
> 
> ![moon (2)](https://private-user-images.githubusercontent.com/30039844/312755276-fa559726-f31a-4a65-a38d-f88c7bd1e787.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMTE3MzcsIm5iZiI6MTcxMzIxMTQzNywicGF0aCI6Ii8zMDAzOTg0NC8zMTI3NTUyNzYtZmE1NTk3MjYtZjMxYS00YTY1LWEzOGQtZjg4YzdiZDFlNzg3LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDIwMDM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5MjE3NmY5Y2E1YWUxYjBiODdkMWI4MGYxNGVkY2YwMGEyY2VlNTE0NTQzMGM3YjFlOGRhOGEyNTZlNDc5ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qEOOjXOpiqm-pTYrcniyy4afAJg6WDMe1n8sOwt-w_0)

Yep it's a bit big, but that'll be good enough

2024-04-19 01:57 UTC, canhtrinh commented on registry/mainnet/interchain/squid.tokenlist.json
> +    "0xf5ddb0c04985ee286ca7930c8dc38bcb5e71f123027cb8886b0dd834578120bd": {
```suggestion
    { "0xf5ddb0c04985ee286ca7930c8dc38bcb5e71f123027cb8886b0dd834578120bd": {
```

2024-04-19 02:04 UTC, canhtrinh approved these changes

2024-04-19 02:06 UTC, merged