feat: add G3 token
axelarnetwork/axelar-configs pull request #40
Opened 2024-04-06 06:03 UTC by SvenMeyer

2024-04-15 19:50 UTC, ecdsafu requested changes
Looks good, think this is missing this image 
https://raw.githubusercontent.com/axelarnetwork/axelar-configs/main/images/tokens/g3.svg

2024-04-21 13:53 UTC, Olanetsoft approved these changes

2024-04-24 14:39 UTC, ecdsafu approved these changes

2024-04-30 14:51 UTC, canhtrinh approved these changes

2024-05-01 03:18 UTC, closed without merging