feat: add ESE token
axelarnetwork/axelar-configs pull request #41
Opened 2024-04-07 11:56 UTC by Juglipaff

2024-04-15 19:50 UTC, ecdsafu requested changes
looks good, but could you replace with this image? Cropped in a circle 
![ese](https://github.com/axelarnetwork/axelar-configs/assets/36089395/4e06f2be-2051-4c5e-9219-ee6de0f9bf25)

2024-04-16 07:53 UTC, Juglipaff commented
@ecdsafu
Sure thing, done✅

2024-04-16 13:17 UTC, ecdsafu commented
> @ecdsafu Sure thing, done✅

Thanks!

2024-04-19 02:42 UTC, canhtrinh approved these changes

2024-04-19 02:42 UTC, merged