feat: add CDFi token
axelarnetwork/axelar-configs pull request #48
Opened 2024-04-17 14:57 UTC by RomanCeDeFi

2024-04-17 15:02 UTC, ecdsafu requested changes
Thanks! Please add the coingecko ID if the token has one, and the image file at        https://raw.githubusercontent.com/axelarnetwork/axelar-configs/main/images/tokens/cdfi.svg

2024-04-22 16:35 UTC, Olanetsoft approved these changes

2024-04-24 14:42 UTC, ecdsafu approved these changes
lgtm

2024-04-30 14:53 UTC, canhtrinh approved these changes

2024-05-01 03:22 UTC, canhtrinh approved these changes

2024-05-01 03:22 UTC, merged