Adds RMRK Logo
axelarnetwork/axelar-configs pull request #7
Opened 2023-12-20 17:54 UTC by steven2308

2023-12-21 19:52 UTC, canhtrinh commented on registry/mainnet/interchain/squid.tokenlist.json
> +        "svg": "https://raw.githubusercontent.com/axelarnetwork/axelar-configs/images/tokens/rmrk.png"
can you provide in svg format

2023-12-27 14:30 UTC, steven2308 commented on registry/mainnet/interchain/squid.tokenlist.json
> +        "svg": "https://raw.githubusercontent.com/axelarnetwork/axelar-configs/images/tokens/rmrk.png"
Fixed!

2024-01-07 22:07 UTC, ecdsafu requested changes
Looks good, please use icons which can be displayed in a circle. I can convert them if you send them to me.
[rmrk.svg.zip](https://github.com/axelarnetwork/axelar-configs/files/13855096/rmrk.svg.zip)

2024-01-08 16:18 UTC, steven2308 commented
> Looks good, please use icons which can be displayed in a circle. I can convert them if you send them to me. [rmrk.svg.zip](https://github.com/axelarnetwork/axelar-configs/files/13855096/rmrk.svg.zip)

I uploaded a new one, thanks!

2024-01-09 21:33 UTC, ecdsafu commented
> > Looks good, please use icons which can be displayed in a circle. I can convert them if you send them to me. [rmrk.svg.zip](https://github.com/axelarnetwork/axelar-configs/files/13855096/rmrk.svg.zip)
> 
> I uploaded a new one, thanks!

Looks great! Thank you 

@canhtrinh could we also have an optional coingeckoId property on these tokens?

2024-01-11 01:59 UTC, canhtrinh approved these changes

2024-01-11 01:59 UTC, merged