Added PSTAKE Token
axelarnetwork/axelar-configs pull request #84
Opened 2024-06-10 16:59 UTC by ChipKlutzy

Please review the following token assets:

## 📑 Description

-   Token Name: pSTAKE Finance
-   Project Website: https://pstake.finance/
-   Explorer URI: https://etherscan.io/token/0xfb5c6815ca3ac72ce9f5006869ae67f18bf77006

2024-06-10 20:20 UTC, blurrytweaks requested changes
Hi chip! could you please add it's coingecko ID below "tokenId":

      "coinGeckoId": "pstake-finance",

2024-06-11 05:20 UTC, ChipKlutzy commented
> Hi chip! could you please add it's coingecko ID below "tokenId":
> 
> ```
>   "coinGeckoId": "pstake-finance",
> ```

Hi @blurrytweaks updated the `coinGeckoId`

2024-06-12 13:17 UTC, ecdsafu approved these changes
lgtm

2024-06-12 18:13 UTC, canhtrinh approved these changes

2024-06-12 18:13 UTC, merged